name: CI Suite

on:
    pull_request:
      branches:
        - master
    merge_group:
      branches:
        - master

jobs:
  start_gate:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Start Gate
    runs-on: ubuntu-24.04
    steps:
        - name: Mandatory Empty Step
          run: exit 0
    
  run_linters:
    name: Run Linters
    needs: start_gate
    uses: ./.github/workflows/run_linters.yml
# 
#  collect_data:
#    name: Collect data and setup caches for other tasks
#    needs: start_gate
#    uses: .
